### ISSUE TITLE
tags (except for tags: private) not picked up on methods

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#20] opened 2012-06-06 22:33 UTC
Methods have various tags, for example in _WidgetBase.js:

``` javascript
postMixInProperties: function(){
    // summary:
    //      Called after the parameters to the widget have been read-in,
    //      but before the widget template is instantiated. Especially
    //      useful to set properties that are referenced in the widget
    //      template.
    // tags:
    //      protected
},
```

They are not being picked up, except for private (#14), but they should be.   According to dojo's code base and it's style guide (http://livedocs.dojotoolkit.org/util/doctools/markup#tags) all tags are supposed to work.

**Comment by csnover** [comment] 2012-06-08 04:17
Duplicate of #13; no tags are being output though they are processed.

**Closed as completed by csnover** 2012-06-08 04:17 UTC
