### ISSUE TITLE
Regression: the inheritance of doc for property and method overrides seems broken

### ISSUE THREAD

**Issue by AdrianVasiliu** [csnover/js-doc-parse#26] opened 2012-06-08 12:45 UTC
In the old Dojo 1.6 API doc, a method override having no doc comments in its source code used to get the doc from the parent class. An example:
http://dojotoolkit.org/api/1.6/dojox/mobile/View#buildRendering
In the XML generated nowadays for such overrides there is no documentation.

Will the doc inheritance be done at the level of XML to HTML conversion? Or will this be fixed at the XML level?
This is important for us to know, because we have to make the choice to either keep our overrides without any doc and count on the inheritance, or to duplicate doc pieces for all our overrides currently with no doc.

**Comment by AdrianVasiliu** [comment] 2012-06-08 15:16
Well, I realize this is a duplicate of https://github.com/csnover/js-doc-parse/issues/21.

**Comment by csnover** [comment] 2012-06-09 05:06
Duplicate of #21.

**Closed as completed by csnover** 2012-06-09 05:06 UTC
